name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 允许发布 Release 和上传文件

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release
        run: cargo build --release --manifest-path clash_log/Cargo.toml

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Rename executable
        run: |
          Move-Item -Path "clash_log/target/release/clash_log.exe" -Destination "clash_log-${{ steps.get_version.outputs.VERSION }}-x86_64-pc-windows-msvc.exe"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: clash_log-${{ steps.get_version.outputs.VERSION }}-x86_64-pc-windows-msvc.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
